### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by hz19990620** [lunarwhite/yolo-student-counter#2]
您好，请问一张图片上的标识框个数的统计是怎么实现的？要改哪部分代码？

**Comment by lunarwhite** [comment]
参考[这个commit](https://github.com/lunarwhite/students-inclassroom-monitoring/commit/77e63a47cfd77152f1767088ac9132c25be3544e)

**Comment by hz19990620** [comment]
> 参考[这个commit](https://github.com/lunarwhite/students-inclassroom-monitoring/commit/77e63a47cfd77152f1767088ac9132c25be3544e)

哥，方便加个联系方式教一下吗？我是本科毕设做这个以前没接触过，有点吃力。V：yh126513 感激不尽
