### ISSUE TITLE
能否提供训练好的权重文件

### ISSUE THREAD

**Issue by luduangit** [lunarwhite/yolo-student-counter#6]
这是一个很棒的项目，有没有训练好的权重文件呢？希望能得到作者的帮助，谢谢！

**Comment by lunarwhite** [comment]
很高兴这个项目对你有帮助，但由于时间跨度比较长，相关数据/文件除了repo里的 其他就没有保留
预训练权重可在 https://github.com/ultralytics/yolov5/releases 下载
